### ISSUE TITLE
ugly font on macos

### ISSUE THREAD

**Issue by glensc** [martenbjork/github-xp#64] opened 2018-06-11 07:16 UTC
![image](https://user-images.githubusercontent.com/199095/41217408-6df5a418-6d60-11e8-9df3-feb03a86b8e9.png)

**Comment by martenbjork** [comment] 2018-06-11 14:00
Duplicate of #3 :)

**Comment by martenbjork** [comment] 2018-06-11 14:03
It's intentional :) #42

**Closed by martenbjork** 2018-06-11 14:03 UTC

**Comment by glensc** [comment] 2018-06-11 18:56
oh. i thought it requires some xp font which is not available on macos and no fallback provided.
