### ISSUE TITLE
[BUG] Wrong title position when using with octotree

### ISSUE THREAD

**Issue by williamokano** [martenbjork/github-xp#34] opened 2018-06-06 16:57 UTC
The title is misplaced when octotree sidebar is open

https://chrome.google.com/webstore/detail/octotree/bkhaagjahfmjljalopjnoealnfndnagc?hl=pt-BR

![image](https://user-images.githubusercontent.com/5909442/41053304-898dcd86-6991-11e8-882e-fe38e486ccb5.png)

**Comment by martenbjork** [comment] 2018-06-06 18:06
Duplicate of #27 . I'll fix it! :)

**Closed by martenbjork** 2018-06-06 18:06 UTC
